### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by Sim0x0** [BishopFox/GitGot#16]
hello ! can you help me fix this error ? >>>>>

Collecting Github Search API data...
Traceback (most recent call last):
  File "./gitgot.py", line 490, in <module>
    main()
  File "./gitgot.py", line 486, in main
    github_search(g, state)
  File "./gitgot.py", line 313, in github_search
    state.totalCount = repositories.totalCount
  File "/usr/local/lib/python3.7/dist-packages/github/PaginatedList.py", line 153, in totalCount
    headers=self.__headers
  File "/usr/local/lib/python3.7/dist-packages/github/Requester.py", line 276, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/local/lib/python3.7/dist-packages/github/Requester.py", line 287, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}

**Comment by the-bumble** [comment]
Hey Sim0x0,

> github.GithubException.BadCredentialsException: 401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}

It looks like your GitHub API key is invalid. See the `README.md` for instructions on setting up a GitHub API key with GitGot. It can either be placed in the `gitgot.py` file or as an environment variable.

Happy hacking!

Jake
